server:
  port: 8002 #端口
spring:
  application:
    name: customer2 #服务名称
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/ #注册中心地址
management:
  port: 8083
  security:
    enable: flase