server:
  port: 8003
spring:
  application:
    name: customer1 #服务名称
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
customer3:
  rabbitmq:
    exchange:
      - name: icao.sale_order
          type: topic
          queues:
            - name: test
              routingKey: 'jf.*'
            - name: hello
              routingKey: JR-ORDER-ROUTING
#就是一个配置注入，做完了就直接读了。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/ #注册中心地址不能通过变量指定
management:
  port: 8082
  security:
    enable: flase